# Build and pushes a docker image to Docker hub using Dockerfile in the root of project.
# You have to pass "tags" parameter with a full path to repository and an image name.
# For example,  test/test:latest
name: Build with docker
on:       
    workflow_call:         
        inputs:
            tags:
                description: "Docker tags"
                required: true
                type: string
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Docker: setup and build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4        
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ inputs.tags }}
          push: true